server {
    listen 25532;
    server_name m.yaml.uk;

    root /var/www/passwall-editor;
    autoindex off;
    default_type application/octet-stream;

    location / {
        try_files $uri =404;
    }
}

